from django.conf.urls.defaults import *


urlpatterns = patterns('librarian.views',
    (r'^$', 'librarian_home'),
    (r'^paper/(?P<list_type>\w+)/$', 'list_paper'),
    (r'^paper/show/(?P<paper_id>\d+)/$', 'show_paper'),
    (r'^person/$', 'list_people'),
    (r'^person/show/(?P<person_id>\d+)/$', 'show_person'),
    (r'^institution/$', 'list_institution'),
    (r'^institution/show/(?P<key>\d+)$', 'show_institution'),
    (r'^country/$', 'list_country'),
    (r'^country/show/(?P<key>\d+)$', 'show_country'),
    (r'^journal/$', 'list_journal'),
    (r'^journal/show/(?P<key>\d+)$', 'show_journal'),
    (r'^add/$', 'add_papers'),
    (r'^import_ISI_data/$', 'import_ISI_data'),
    (r'^update_ISI_data/$', 'update_ISI_data'),
    (r'^import_state/$', 'import_state'),
    (r'^add_progress/$', 'add_progress'),
    (r'^update_citation/$', 'update_citation'),
    (r'^update_citations/$', 'update_citations'),
    (r'^update_SBW/(?P<cl>\w+)/$', 'update_SBW_view'),
    (r'^update_SBW_entity/$', 'update_SBW_entity'),
    (r'^update_raw_cit/$', 'update_raw_cit'),
    (r'^update_journal/$', 'update_journal'),
    (r'^to_import/$', 'to_import'),
    (r'^correct_journals/(?P<ran>\d+)/$', 'correct_journals'),
    #~ (r'^search/$', 'search'),
)
